apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "TKH-Maybank-Organization-test2"
  links:
  - url: https://dashboard.example.com
    title: Test Backstage Dashboard
    icon: dashboard
  annotations:
    github.com/project-slug: tkhmaybank/TKH-Maybank-Organization-test2
    backstage.io/techdocs-ref: ./README.md
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
